import { Incident, FBOProfile, DispatchEvent } from '../types';

export const INITIAL_INCIDENTS: Incident[] = [
  {
    incident_id: 'SRK-2026-88392',
    timestamp: '2026-08-19T14:20:00Z',
    city: 'Bengaluru',
    state: 'Karnataka',
    ward: 'Koramangala Ward 68',
    lat: 12.9352,
    lng: 77.6244,
    fbo_name: 'Zomato Cloud Kitchen Koramangala',
    fbo_slug: 'zomato-cloud-kitchen-koramangala',
    fssai_license: '11223344556677',
    fssai_verified: true,
    category: 'Cloud Kitchen',
    hazard_primary: 'FOREIGN_OBJECT',
    hazard_severity: 'P0_CRITICAL',
    user_description: 'Found a dead cockroach inside packed biryani container.',
    evidence_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    phash_flags: [],
    merchant_response: 'They ignored me',
    refund_received: false,
    action_requested: 'FSO inspection',
    moderation_status: 'APPROVED',
    auto_approved: true,
    cluster_id: 'CLU-2026-441',
    fso_status: 'Under FSO Review',
    upvotes: 14,
    ddo_email: 'ddo.karnataka.bangalore@fssai.gov.in'
  },
  {
    incident_id: 'SRK-2026-88393',
    timestamp: '2026-08-19T12:05:00Z',
    city: 'Bengaluru',
    state: 'Karnataka',
    ward: 'Koramangala Ward 68',
    lat: 12.9360,
    lng: 77.6250,
    fbo_name: 'Zomato Cloud Kitchen Koramangala',
    fbo_slug: 'zomato-cloud-kitchen-koramangala',
    fssai_license: '11223344556677',
    fssai_verified: true,
    category: 'Cloud Kitchen',
    hazard_primary: 'FOREIGN_OBJECT',
    hazard_severity: 'P0_CRITICAL',
    user_description: 'Metal piece/stapler pin inside raita container.',
    evidence_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
    phash_flags: [],
    merchant_response: 'They replaced / refunded',
    refund_received: true,
    action_requested: 'Formal FSSAI complaint',
    moderation_status: 'APPROVED',
    auto_approved: true,
    cluster_id: 'CLU-2026-441',
    fso_status: 'Under FSO Review',
    upvotes: 9,
    ddo_email: 'ddo.karnataka.bangalore@fssai.gov.in'
  },
  {
    incident_id: 'SRK-2026-88394',
    timestamp: '2026-08-18T19:30:00Z',
    city: 'Bengaluru',
    state: 'Karnataka',
    ward: 'Koramangala Ward 68',
    lat: 12.9348,
    lng: 77.6240,
    fbo_name: 'Zomato Cloud Kitchen Koramangala',
    fbo_slug: 'zomato-cloud-kitchen-koramangala',
    fssai_license: '11223344556677',
    fssai_verified: true,
    category: 'Cloud Kitchen',
    hazard_primary: 'SPOILED_MOLD',
    hazard_severity: 'P1_MODERATE',
    user_description: 'Sour, foul-smelling dal with visible white mold on surface.',
    evidence_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    phash_flags: [],
    merchant_response: 'They denied the problem',
    refund_received: false,
    action_requested: 'FSO inspection',
    moderation_status: 'APPROVED',
    auto_approved: true,
    cluster_id: 'CLU-2026-441',
    fso_status: 'Under FSO Review',
    upvotes: 6,
    ddo_email: 'ddo.karnataka.bangalore@fssai.gov.in'
  },
  {
    incident_id: 'SRK-2026-88395',
    timestamp: '2026-08-19T11:15:00Z',
    city: 'Bengaluru',
    state: 'Karnataka',
    ward: 'Indiranagar Ward 80',
    lat: 12.9784,
    lng: 77.6408,
    fbo_name: 'Royal Biryani House Indiranagar',
    fbo_slug: 'royal-biryani-house-indiranagar',
    fssai_license: '11229988776655',
    fssai_verified: true,
    category: 'Restaurant / Café',
    hazard_primary: 'VEG_NONVEG_CONTAMINATION',
    hazard_severity: 'P0_CRITICAL',
    user_description: 'Chicken bone piece found inside pure vegetarian Paneer Butter Masala gravy.',
    evidence_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80',
    phash_flags: [],
    merchant_response: 'They denied the problem',
    refund_received: false,
    action_requested: 'Formal FSSAI complaint',
    moderation_status: 'APPROVED',
    auto_approved: true,
    fso_status: 'Pending Review',
    upvotes: 22,
    ddo_email: 'ddo.karnataka.bangalore@fssai.gov.in'
  },
  {
    incident_id: 'SRK-2026-88396',
    timestamp: '2026-08-19T09:40:00Z',
    city: 'Mumbai',
    state: 'Maharashtra',
    ward: 'Andheri West K-West',
    lat: 19.1197,
    lng: 72.8464,
    fbo_name: 'Fresh Farm Dairy & Sweets',
    fbo_slug: 'fresh-farm-dairy-sweets',
    fssai_license: '21518001000456',
    fssai_verified: true,
    category: 'Sweet Shop / Mithai',
    hazard_primary: 'CHEMICAL_ADULTERANT',
    hazard_severity: 'P0_CRITICAL',
    user_description: 'Synthetic milk curd with detergent smell causing burning throat sensation.',
    evidence_url: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=600&auto=format&fit=crop&q=80',
    phash_flags: [],
    merchant_response: 'They ignored me',
    refund_received: false,
    action_requested: 'Formal FSSAI complaint',
    moderation_status: 'APPROVED',
    auto_approved: true,
    fso_status: 'FSO Inspection Scheduled',
    upvotes: 31,
    ddo_email: 'ddo.mumbai.fssai@maharashtra.gov.in'
  },
  {
    incident_id: 'SRK-2026-88397',
    timestamp: '2026-08-18T16:10:00Z',
    city: 'Mumbai',
    state: 'Maharashtra',
    ward: 'Bandra West H-West',
    lat: 19.0596,
    lng: 72.8295,
    fbo_name: 'Bandra Chaat Corner',
    fbo_slug: 'bandra-chaat-corner',
    fssai_license: '21520005000123',
    fssai_verified: false,
    category: 'Street Vendor / Stall',
    hazard_primary: 'FOOD_POISONING',
    hazard_severity: 'P0_CRITICAL',
    user_description: '3 family members admitted to local clinic with acute gastroenteritis after pani puri.',
    evidence_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80',
    phash_flags: [],
    merchant_response: 'Haven\'t told them yet',
    refund_received: false,
    action_requested: 'FSO inspection',
    moderation_status: 'APPROVED',
    auto_approved: true,
    fso_status: 'Inspected & Action Taken',
    upvotes: 45,
    ddo_email: 'ddo.mumbai.fssai@maharashtra.gov.in'
  },
  {
    incident_id: 'SRK-2026-88398',
    timestamp: '2026-08-19T14:45:00Z',
    city: 'Delhi',
    state: 'Delhi',
    ward: 'Connaught Place Central',
    lat: 28.6315,
    lng: 77.2167,
    fbo_name: 'CP Food Hall Supermarket',
    fbo_slug: 'cp-food-hall-supermarket',
    fssai_license: '10012011000111',
    fssai_verified: true,
    category: 'Packaged Food',
    hazard_primary: 'EXPIRED_PRODUCT',
    hazard_severity: 'P1_MODERATE',
    user_description: 'Infant cereal packet sold with tampered expiry date (expired May 2026).',
    evidence_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    phash_flags: [],
    merchant_response: 'They replaced / refunded',
    refund_received: true,
    action_requested: 'Public awareness only',
    moderation_status: 'APPROVED',
    auto_approved: true,
    fso_status: 'Pending Review',
    upvotes: 8,
    ddo_email: 'fso.delhi.central@delhi.gov.in'
  },
  {
    incident_id: 'SRK-2026-88399',
    timestamp: '2026-08-19T15:00:00Z',
    city: 'Patna',
    state: 'Bihar',
    ward: 'Kankarbagh Ward 12',
    lat: 25.5941,
    lng: 85.1376,
    fbo_name: 'Fair Price PDS Ration Shop #42',
    fbo_slug: 'fair-price-pds-ration-shop-42',
    fssai_license: '10419001000888',
    fssai_verified: false,
    category: 'PDS / Ration Shop',
    hazard_primary: 'PDS_ADULTERATION',
    hazard_severity: 'P2_ADVISORY',
    user_description: 'Rice bag distributed under PMGKAY infested with weevils and white chalk powder.',
    evidence_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    phash_flags: [],
    merchant_response: 'They denied the problem',
    refund_received: false,
    action_requested: 'Formal FSSAI complaint',
    moderation_status: 'APPROVED',
    auto_approved: true,
    fso_status: 'Under FSO Review',
    upvotes: 52,
    ddo_email: 'civilsupplies.patna@bihar.gov.in'
  },
  {
    incident_id: 'SRK-2026-99001',
    timestamp: '2026-08-19T15:10:00Z',
    city: 'Bengaluru',
    state: 'Karnataka',
    ward: 'Whitefield Ward 84',
    lat: 12.9698,
    lng: 77.7499,
    fbo_name: 'Whitefield Dosa Corner',
    fbo_slug: 'whitefield-dosa-corner',
    fssai_license: '11224455667788',
    fssai_verified: false,
    category: 'Street Vendor / Stall',
    hazard_primary: 'FOREIGN_OBJECT',
    hazard_severity: 'P0_CRITICAL',
    user_description: 'Found thin metal copper wire fried inside masala dosa.',
    evidence_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80',
    phash_flags: ['Low confidence business name match'],
    merchant_response: 'Haven\'t told them yet',
    refund_received: false,
    action_requested: 'FSO inspection',
    moderation_status: 'PENDING',
    auto_approved: false,
    fso_status: 'Pending Review',
    upvotes: 1,
    ddo_email: 'ddo.karnataka.bangalore@fssai.gov.in'
  }
];

export const INITIAL_DISPATCHES: DispatchEvent[] = [
  {
    dispatch_id: 'DISP-2026-101',
    cluster_id: 'CLU-2026-441',
    fbo_name: 'Zomato Cloud Kitchen Koramangala',
    fssai_license: '11223344556677',
    city: 'Bengaluru',
    ddo_email: 'ddo.karnataka.bangalore@fssai.gov.in',
    report_count: 3,
    p0_count: 2,
    triggered_at: '2026-08-19T13:00:00Z',
    status: 'ACKNOWLEDGED',
    fso_response_date: '2026-08-19T14:30:00Z'
  },
  {
    dispatch_id: 'DISP-2026-102',
    cluster_id: 'CLU-2026-389',
    fbo_name: 'Fresh Farm Dairy & Sweets',
    fssai_license: '21518001000456',
    city: 'Mumbai',
    ddo_email: 'ddo.mumbai.fssai@maharashtra.gov.in',
    report_count: 4,
    p0_count: 3,
    triggered_at: '2026-08-18T10:00:00Z',
    status: 'INSPECTED',
    fso_response_date: '2026-08-19T11:00:00Z'
  }
];
